---
- name: Install Redis
  apt:
    name: redis-server

- name: Install Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    force: true
    owner: "redis"
    mode: 0644

- name: Install Redis Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/redis.conf
    force: true
    mode: 0644

- name: Disable Redis services
  service:
    name: "redis-server"
    enabled: false
    state: stopped
