---
- name: Make console executable
  become: true
  become_user: azuracast
  shell: >-
    chmod +x {{ www_base }}/backend/bin/*

- name: Run AzuraCast Setup (Install Mode)
  become: true
  become_user: azuracast
  shell: >-
    azuracast_cli azuracast:setup
  when: not update_mode|bool

- name: Migrate Legacy Configuration (Update Mode)
  become: true
  become_user: azuracast
  shell: >-
    azuracast_cli azuracast:setup:migrate
  when: update_mode|bool

- name: Run AzuraCast Setup (Update Mode)
  become: true
  become_user: azuracast
  shell: >-
    azuracast_cli azuracast:setup --update
  when: update_mode|bool
