---
- name: Install Deb Multimedia Repository
  include_tasks: dmo.yml

- name: Install Icecast
  include_tasks: icecast.yml

- name: Install Liquidsoap
  include_tasks: liquidsoap.yml

- name: Install Audiowaveform
  apt:
    deb: "https://github.com/bbc/audiowaveform/releases/download/{{ audiowaveform_version }}/audiowaveform_{{ audiowaveform_version }}-1-{{ debian_version }}_{{ deb_arch }}.deb"

- name: Install Flac
  apt:
    name: flac
    install_recommends: false

- name: Install Vorbis-Tools
  apt:
    name: vorbis-tools
    install_recommends: false
