---
- hosts: all
  become: true

  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - init
    - azuracast-user
    - azuracast-config
    - azuracast-radio
    - azuracast-startup
    - supervisord
    - nginx
    - php
    - centrifugo
    - redis
    - beanstalkd
    - sftpgo
    - mariadb
    - superchronic
    - influxdb
    - ufw
    - dbip
    - composer
    - services
    - azuracast-db-install
    - azuracast-build
    - azuracast-setup
