---
- name: "Running context"
  debug:
    msg: >-
      Running Ansible on {{ inventory_hostname }} with OS {{ ansible_distribution }} {{ ansible_distribution_release }}
      {{ ansible_distribution_version }} {{ ansible_architecture }} ({{ app_env }})

- name: "Shut down all services"
  service:
    name: "{{ uninstall_svc_to_stop }}"
    state: stopped
  loop:
    - "mysql"
    - "php{{ php_version }}-fpm"
    - "nginx"
    - "redis-server"
    - "supervisor"
    - "centrifugo"
  loop_control:
    loop_var: uninstall_svc_to_stop
  ignore_errors: true

- name: Kill all processes owned by AzuraCast user
  command: pkill -9 -u azuracast
  ignore_errors: true

- name: Update apt
  apt:
    update_cache: true

- name: Remove AzuraCast User
  user:
    name: azuracast
    state: absent

- name: "Remove AzuraCast folders"
  file:
    path: "{{ uninstall_file_to_delete }}"
    state: absent
  loop:
    - "{{ tmp_base }}"
    - "{{ app_base }}/servers"
  loop_control:
    loop_var: uninstall_file_to_delete

- name: UFW - Turn off Firewall
  ufw:
    state: disabled
  ignore_errors: true

- name: Remove software
  apt:
    name: "{{ packages }}"
    state: absent
    force: true
    purge: true
  vars:
    packages:
      # Icecast2
      - icecast2
      - libxml2
      - libxslt1-dev
      - libvorbis-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - pkg-config

      # LiquidSoap
      - liquidsoap
      - libao-dev
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libfaad-dev
      - libfdk-aac-dev
      - libflac-dev
      - libfreetype-dev
      - libgd-dev
      - libjack-dev
      - libjpeg-dev
      - liblo-dev
      - libmad0-dev
      - libmagic-dev
      - libmp3lame-dev
      - libopus-dev
      - libpng-dev
      - libportaudio2
      - libpulse-dev
      - libsamplerate0-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-image-dev
      - libshine-dev
      - libsoundtouch-dev
      - libspeex-dev
      - libsrt-openssl-dev
      - libswresample-dev
      - libswscale-dev
      - libtag1-dev
      - libtheora-dev
      - libtiff-dev
      - libx11-dev
      - libxpm-dev
      - bubblewrap
      - ffmpeg
      - frei0r-plugins-dev
      - ladspa-sdk
      - multimedia-audio-plugins
      - swh-plugins
      - tap-plugins
      - lsp-plugins-ladspa

      # Codecs
      - vorbis-tools
      - flac

      # Cron
      - cron
      - tmpreaper

      # Beanstalkd
      - beanstalkd

      # MariaDB
      - mariadb-*
      - python3-pymysql

      # Nginx
      - nginx
      - nginx-*

      # PHP
      - php-*
      - php{{ php_version }}-*

      # Redis
      - redis-server

      # SFTPGo
      - sftpgo

      # Supervisord
      - supervisor

      # UFW Firewall
      - ufw

      # System packages
      - pwgen
      - lnav
